/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2026 vLabel Project
 * All rights reserved.
 *
 * vLabel Audit Subsystem
 *
 * Provides a ring buffer for audit events that can be read from /dev/vlabel.
 * Events are generated by access checks and delivered to userland daemons.
 */

#include <sys/param.h>
#include <sys/systm.h>
#include <sys/kernel.h>
#include <sys/jail.h>
#include <sys/lock.h>
#include <sys/malloc.h>
#include <sys/module.h>
#include <sys/mutex.h>
#include <sys/poll.h>
#include <sys/proc.h>
#include <sys/selinfo.h>
#include <sys/sysctl.h>
#include <sys/ucred.h>
#include <sys/vnode.h>

#include <machine/atomic.h>

#include <security/mac/mac_policy.h>

#include "mac_vlabel.h"

/*
 * Ring buffer size - must be power of 2 for efficient modulo
 */
#define VLABEL_AUDIT_BUFSIZE	256
#define VLABEL_AUDIT_MASK	(VLABEL_AUDIT_BUFSIZE - 1)

/*
 * Audit ring buffer
 */
static struct vlabel_audit_entry vlabel_audit_buf[VLABEL_AUDIT_BUFSIZE];
static volatile u_int vlabel_audit_head;	/* Next write position */
static volatile u_int vlabel_audit_tail;	/* Next read position */
static struct mtx vlabel_audit_mtx;
static struct selinfo vlabel_audit_selinfo;

/*
 * Shutdown flag - set during module unload to prevent new events
 */
static volatile int vlabel_audit_shutdown;

/*
 * Statistics
 */
static uint64_t vlabel_audit_events;		/* Total events generated */
static uint64_t vlabel_audit_dropped;		/* Events dropped (buffer full) */

SYSCTL_DECL(_security_mac_vlabel);
SYSCTL_UQUAD(_security_mac_vlabel, OID_AUTO, audit_events, CTLFLAG_RD,
    &vlabel_audit_events, 0, "Total audit events generated");
SYSCTL_UQUAD(_security_mac_vlabel, OID_AUTO, audit_dropped, CTLFLAG_RD,
    &vlabel_audit_dropped, 0, "Audit events dropped (buffer full)");

/*
 * vlabel_audit_init - Initialize the audit subsystem
 */
void
vlabel_audit_init(void)
{

	mtx_init(&vlabel_audit_mtx, "vlabel_audit", NULL, MTX_DEF);
	knlist_init_mtx(&vlabel_audit_selinfo.si_note, &vlabel_audit_mtx);
	vlabel_audit_head = 0;
	vlabel_audit_tail = 0;
	vlabel_audit_events = 0;
	vlabel_audit_dropped = 0;
	vlabel_audit_shutdown = 0;

	VLABEL_DPRINTF("audit subsystem initialized");
}

/*
 * vlabel_audit_destroy - Destroy the audit subsystem
 */
void
vlabel_audit_destroy(void)
{

	/*
	 * Set shutdown flag first to prevent new events from being logged.
	 * This prevents a race where vlabel_audit_log() could try to acquire
	 * the mutex after we've destroyed it.
	 */
	vlabel_audit_shutdown = 1;

	/* Memory barrier to ensure shutdown flag is visible to other CPUs */
	mb();

	mtx_lock(&vlabel_audit_mtx);

	/* Clear any waiting readers - must hold lock for selwakeup */
	wakeup(&vlabel_audit_buf);
	selwakeup(&vlabel_audit_selinfo);

	mtx_unlock(&vlabel_audit_mtx);

	/*
	 * Drain pending select/poll references, then destroy knlist.
	 * seldrain() waits for all selrecord() references to be released.
	 */
	seldrain(&vlabel_audit_selinfo);
	knlist_destroy(&vlabel_audit_selinfo.si_note);

	mtx_destroy(&vlabel_audit_mtx);

	VLABEL_DPRINTF("audit subsystem destroyed (events=%ju, dropped=%ju)",
	    (uintmax_t)vlabel_audit_events, (uintmax_t)vlabel_audit_dropped);
}

/*
 * vlabel_audit_log - Log an audit event
 *
 * @event_type: Type of event (e.g., operation type)
 * @cred: Credential of the subject
 * @vp: Vnode being accessed (may be NULL)
 * @operation: Operation bitmask
 * @result: Result of the access check (0 = allowed, error = denied)
 *
 * This function is called from check paths and must be fast.
 * If the buffer is full, events are dropped.
 */
void
vlabel_audit_log(uint32_t event_type, struct ucred *cred,
    struct vnode *vp, uint32_t operation, int result)
{
	struct vlabel_audit_entry *entry;
	struct vlabel_label *subj_label;
	struct vlabel_label *obj_label;
	u_int head, next;

	/* Check if shutdown is in progress */
	if (vlabel_audit_shutdown)
		return;

	/* Check if auditing is enabled for this event */
	if (vlabel_audit_level == VLABEL_AUDIT_NONE)
		return;
	if (vlabel_audit_level == VLABEL_AUDIT_DENIALS && result == 0)
		return;

	mtx_lock(&vlabel_audit_mtx);

	/* Double-check shutdown after acquiring lock */
	if (vlabel_audit_shutdown) {
		mtx_unlock(&vlabel_audit_mtx);
		return;
	}

	/* Check for buffer space */
	head = vlabel_audit_head;
	next = (head + 1) & VLABEL_AUDIT_MASK;
	if (next == vlabel_audit_tail) {
		/* Buffer full - drop event */
		mtx_unlock(&vlabel_audit_mtx);
		atomic_add_64(&vlabel_audit_dropped, 1);
		return;
	}

	/* Fill in the audit entry */
	entry = &vlabel_audit_buf[head];
	entry->vae_timestamp = (uint64_t)time_second;
	entry->vae_type = event_type;
	entry->vae_operation = operation;
	entry->vae_result = result;

	/* Process info */
	if (cred != NULL) {
		entry->vae_pid = (curproc != NULL) ? curproc->p_pid : 0;
		entry->vae_uid = cred->cr_uid;
		if (cred->cr_prison != NULL)
			entry->vae_jailid = cred->cr_prison->pr_id;
		else
			entry->vae_jailid = 0;

		/* Subject label */
		if (cred->cr_label != NULL) {
			subj_label = SLOT(cred->cr_label);
			if (subj_label != NULL) {
				strlcpy(entry->vae_subject_label,
				    subj_label->vl_raw,
				    sizeof(entry->vae_subject_label));
			} else {
				entry->vae_subject_label[0] = '\0';
			}
		} else {
			entry->vae_subject_label[0] = '\0';
		}
	} else {
		entry->vae_pid = 0;
		entry->vae_uid = 0;
		entry->vae_jailid = 0;
		entry->vae_subject_label[0] = '\0';
	}

	/* Object label (from vnode if available) */
	if (vp != NULL && vp->v_label != NULL) {
		obj_label = SLOT(vp->v_label);
		if (obj_label != NULL) {
			strlcpy(entry->vae_object_label, obj_label->vl_raw,
			    sizeof(entry->vae_object_label));
		} else {
			entry->vae_object_label[0] = '\0';
		}
	} else {
		entry->vae_object_label[0] = '\0';
	}

	/* We don't have path easily available in check hooks, leave empty */
	entry->vae_path[0] = '\0';

	/* Advance head */
	vlabel_audit_head = next;
	atomic_add_64(&vlabel_audit_events, 1);

	/* Wake up any readers - must be done while holding lock */
	wakeup(&vlabel_audit_buf);
	selwakeup(&vlabel_audit_selinfo);

	mtx_unlock(&vlabel_audit_mtx);
}

/*
 * vlabel_audit_read - Read audit events from the ring buffer
 *
 * Called from vlabel_dev_read() in vlabel_dev.c
 *
 * @uio: User I/O structure
 * @ioflag: I/O flags (IO_NDELAY for non-blocking)
 *
 * Returns 0 on success, error code on failure.
 *
 * Design: We copy one entry at a time while holding the lock, then
 * release the lock to call uiomove (which can sleep/fault). This is
 * safe because we fully consume each entry before releasing the lock.
 * Multiple concurrent readers will each get different entries.
 */
int
vlabel_audit_read(struct uio *uio, int ioflag)
{
	struct vlabel_audit_entry entry;
	int error;

	/* Need at least one entry worth of space */
	if (uio->uio_resid < (ssize_t)sizeof(entry))
		return (EINVAL);

	/* Check if shutdown is in progress */
	if (vlabel_audit_shutdown)
		return (ENXIO);

	mtx_lock(&vlabel_audit_mtx);

	/* Wait for data if buffer is empty */
	while (vlabel_audit_head == vlabel_audit_tail) {
		if (ioflag & IO_NDELAY) {
			mtx_unlock(&vlabel_audit_mtx);
			return (EAGAIN);
		}
		error = msleep(&vlabel_audit_buf, &vlabel_audit_mtx,
		    PCATCH, "vlaudit", 0);
		if (error != 0) {
			mtx_unlock(&vlabel_audit_mtx);
			return (error);
		}
	}

	/*
	 * Copy one entry at a time. We copy the entry and advance tail
	 * atomically while holding the lock, then release the lock to
	 * copy to userspace. This allows multiple readers to work
	 * correctly - each reader gets distinct entries.
	 */
	while (uio->uio_resid >= (ssize_t)sizeof(entry) &&
	    vlabel_audit_head != vlabel_audit_tail) {
		/* Copy entry and advance tail while holding lock */
		entry = vlabel_audit_buf[vlabel_audit_tail];
		vlabel_audit_tail = (vlabel_audit_tail + 1) & VLABEL_AUDIT_MASK;

		mtx_unlock(&vlabel_audit_mtx);

		/* uiomove can sleep/page fault - must not hold lock */
		error = uiomove(&entry, sizeof(entry), uio);
		if (error != 0)
			return (error);

		mtx_lock(&vlabel_audit_mtx);
	}

	mtx_unlock(&vlabel_audit_mtx);
	return (0);
}

/*
 * vlabel_audit_poll - Poll for audit events
 *
 * Called from vlabel_dev_poll() in vlabel_dev.c
 *
 * @events: Events to poll for
 * @td: Current thread
 *
 * Returns bitmask of ready events.
 */
int
vlabel_audit_poll(int events, struct thread *td)
{
	int revents = 0;

	/* Check if shutdown is in progress */
	if (vlabel_audit_shutdown)
		return (POLLHUP);

	mtx_lock(&vlabel_audit_mtx);

	if (events & (POLLIN | POLLRDNORM)) {
		if (vlabel_audit_head != vlabel_audit_tail)
			revents |= events & (POLLIN | POLLRDNORM);
		else
			selrecord(td, &vlabel_audit_selinfo);
	}

	mtx_unlock(&vlabel_audit_mtx);
	return (revents);
}

/*
 * vlabel_audit_count - Return number of pending audit events
 */
u_int
vlabel_audit_count(void)
{
	u_int head, tail;

	head = vlabel_audit_head;
	tail = vlabel_audit_tail;

	return ((head - tail) & VLABEL_AUDIT_MASK);
}
